- hosts: master
  tasks:
    - name: copy kubeconfig from master to local
      become: yes
      #become_user: ubuntu
      fetch:
        src: /home/ubuntu/.kube/config
        dest: kubeconfig
        flat: yes
